import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"

import { ClerkProvider } from "@clerk/nextjs"
import { ThemeProvider } from "@/providers/theme-provider"
import { ClientProvider } from "@/providers/client-provider"
import { Toaster } from "@/components/ui/toaster"
import { Toaster as SonnerToaster } from "@/components/ui/sonner"
// import { Wrapper } from "@/components/wrapper"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClientProvider>
              {/* <Wrapper>{children}</Wrapper> */}
              {children}

              <Toaster />
              <SonnerToaster />
            </ClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
