import type { Metadata } from "next"
import "./styles/globals.css"

import Providers from "./providers"
import { Inter } from "next/font/google"
import Container from "@/components/common/container"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-muted`}>
        <Providers>
          <Container>{children}</Container>
        </Providers>
      </body>
    </html>
  )
}
